---
- hosts: localhost
  tasks:
   - name: Launching ec2 instance
     ec2: 
       key_name: ansible_key_new 
       instance_type: t2.micro
       image: ami-0b44050b2d893d5f7 
       region: ap-south-1
       instance_tags:
         Name: ubuntu-node
