---
- hosts: localhost
  tasks:
   - name: Launching ec2 instance
     ec2: 
       key_name: ansible_key_new 
       instance_type: t2.micro
       image: ami-0b44050b2d893d5f7 
       region: ap-south-1
       instance_tags:
         Name: Ansible_master
       count_tag:
         Name: Ansible_master
       exact_count: 1
   - name: Launching ec2 instance
     ec2:
       key_name: ansible_key_new
       instance_type: t2.micro
       image: ami-052c08d70def0ac62
       region: ap-south-1
       instance_tags:
         Name: RHEL_node_ansible
       count_tag:
         Name: RHEL_node_ansible
       exact_count: 1
