---
- hosts: all
  tasks:
          - name: Including user var
            include_vars:
                    file: users.yaml
          - name: creating user
            user:
                    name: "{{ item }}"
                    state: present
            loop: 
                   "{{ users }}"
